import type { AiAgent } from './agent.types.js';

export const defaultAgents: AiAgent[] = [
  {
    id: 'quick-answer',
    name: '快速问答',
    description: '适合直接向模型提问，快速获得结构化答案。',
    icon: 'chat',
    builtIn: true,
    capabilities: ['chat', 'fileUpload', 'mention'],
    runMode: 'quick',
    systemPrompt: '你是一个高效、准确的 AI 助手，回答要简洁清楚。',
    tools: [],
    skills: ['通用问答'],
    retrievalStrategy: 'semantic',
    webSearchEnabled: false,
    multimodal: { imageUpload: false, fileUpload: true },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'reasoning',
    name: '智能推理',
    description: '适合复杂任务拆解、策略推演和多步骤分析。',
    icon: 'cube',
    builtIn: true,
    capabilities: ['chat', 'reasoning', 'fileUpload', 'mention'],
    runMode: 'reasoning',
    systemPrompt: '你是一个擅长推理和拆解复杂问题的智能体。',
    tools: ['任务拆解', '步骤推理'],
    skills: ['复杂问题分析'],
    retrievalStrategy: 'hybrid',
    webSearchEnabled: false,
    multimodal: { imageUpload: false, fileUpload: true },
    createdAt: new Date().toISOString(),
  },
  {
    id: 'data-analyst',
    name: '数据分析师',
    description: '适合指标分析、表格解释和运营数据洞察。',
    icon: 'chart',
    builtIn: true,
    capabilities: ['chat', 'analysis', 'fileUpload'],
    runMode: 'quick',
    systemPrompt: '你是一个严谨的数据分析师，善于用指标和结论表达。',
    tools: ['指标解释'],
    skills: ['数据洞察'],
    retrievalStrategy: 'keyword',
    webSearchEnabled: false,
    multimodal: { imageUpload: false, fileUpload: true },
    createdAt: new Date().toISOString(),
  },
];
