import { CURRENT_JSON_VIDEO_VERSION } from "../src/JsonVideo/schema";

export const remotionVideoCapabilities = {
  service: "agent-tool-remotion-video",
  compositionId: "JsonVideo",
  schemaVersion: CURRENT_JSON_VIDEO_VERSION,
  elementTypes: [
    "text",
    "shape",
    "image",
    "video",
    "audio",
    "gif",
    "captions",
  ],
  animationTypes: [
    "fade-in",
    "fade-out",
    "slide-in",
    "slide-out",
    "scale-in",
    "scale-out",
    "rotate-in",
    "rotate-out",
    "spring-in",
    "blur-in",
    "blur-out",
    "reveal-in",
    "bounce-in",
    "pulse",
    "shake",
    "float",
    "ken-burns",
    "typewriter",
    "count-up",
  ],
  transitionTypes: [
    "fade",
    "slide",
    "wipe",
    "dissolve",
    "clock-wipe",
    "iris",
    "flip",
  ],
  limits: {
    maxDurationInFrames: 18000,
    maxElementsPerTimeline: 100,
    maxScenes: 100,
    maxAnimationsPerElement: 12,
    maxCaptionItems: 5000,
  },
} as const;
