import type { ContentResourceType } from '../../../../types';
import type { ResourceCopy, WorksFunctionOption } from './pageTypes';

export const allWorksFunctionOption: WorksFunctionOption = {
  key: 'all',
  label: '全部功能',
  modeKeys: [],
  modeTitles: [],
};

export const imageWorksFunctionOptions: WorksFunctionOption[] = [
  { key: 'image:dialog', label: '对话生图', modeKeys: ['dialog'], modeTitles: ['对话生图'] },
  { key: 'image:detail', label: '详情图生成', modeKeys: ['detail'], modeTitles: ['详情图生成'] },
  { key: 'image:outfit', label: '换装', modeKeys: ['outfit'], modeTitles: ['换装'] },
  { key: 'image:model-views', label: '模特三视图', modeKeys: ['model-views'], modeTitles: ['模特三视图'] },
  { key: 'image:pose-reference', label: '姿势参考', modeKeys: ['pose-reference'], modeTitles: ['姿势参考'] },
  { key: 'image:upscale', label: '高清放大', modeKeys: ['upscale'], modeTitles: ['高清放大'] },
  { key: 'image:cutout', label: '图片抠图', modeKeys: ['cutout'], modeTitles: ['图片抠图'] },
  { key: 'image:background', label: '换背景', modeKeys: ['background'], modeTitles: ['换背景'] },
  { key: 'image:scene-extract', label: '场景提取', modeKeys: ['scene-extract'], modeTitles: ['场景提取'] },
  { key: 'image:model-face-swap', label: '模特换脸', modeKeys: ['model-face-swap'], modeTitles: ['模特换脸'] },
  { key: 'image:head-swap', label: '智能换头', modeKeys: ['head-swap'], modeTitles: ['智能换头'] },
  { key: 'image:face-swap', label: '智能换脸', modeKeys: ['face-swap'], modeTitles: ['智能换脸'] },
  { key: 'image:redraw', label: '智能重绘', modeKeys: ['redraw'], modeTitles: ['智能重绘'] },
  { key: 'image:detail-enhance', label: '细节增强', modeKeys: ['detail-enhance'], modeTitles: ['细节增强'] },
  { key: 'image:print-extract', label: '印花提取', modeKeys: ['print-extract'], modeTitles: ['印花提取'] },
  { key: 'image:face-enhance', label: '脸部增强', modeKeys: ['face-enhance'], modeTitles: ['脸部增强'] },
];

export const videoWorksFunctionOptions: WorksFunctionOption[] = [
  { key: 'video:all', label: '视频生成', modeKeys: [], modeTitles: [] },
  { key: 'video:creation', label: '视频生成-视频创作', modeKeys: [], modeTitles: [] },
  { key: 'video:talking-video', label: '视频生成-口播视频生成', modeKeys: [], modeTitles: [] },
  { key: 'video:upscale', label: '视频生成-高清放大', modeKeys: [], modeTitles: [] },
  { key: 'video:subtitle-removal', label: '视频生成-字幕擦除', modeKeys: [], modeTitles: [] },
  { key: 'video:translation', label: '视频生成-视频翻译', modeKeys: [], modeTitles: [] },
];

export const showWorksBatchButton = false;
export const finishedAssetsPageSize = 20;

export const resourceCopy: Record<ContentResourceType, ResourceCopy> = {
  digital_human: {
    breadcrumb: '素材库 / 数字人形象',
    icon: '👤',
    defaultGroup: '数字人项目',
    pageTitle: '数字人形象',
    pageDescription: '上传本人清晰照片，沉淀为可用于视频出镜的数字人项目；项目内可管理训练照片、三视图素材和后续生成结果。',
    steps: ['上传本人照片', '生成人物三视图', '用于视频出镜'],
    addTitle: '新增数字人',
    addHint: '创建人物档案并上传照片',
    nameLabel: '数字人名称',
    namePlaceholder: '例如：创始人口播、客服小陈、导购形象',
    uploadTitle: '上传本人照片',
    uploadHint: '建议上传正脸、半身、不同角度的清晰照片；后续可生成正面/侧面/背面三视图',
    createOkText: '创建数字人项目',
    emptyGroups: '暂无数字人项目，可创建人物档案后上传照片。',
    emptyAssets: '该数字人暂无照片或三视图素材，可以上传本人照片后继续生成。',
    detailUploadText: '上传照片',
    detailAddText: '添加照片',
    assetUnit: '张照片',
    accept: 'image/*',
  },
  virtual_portrait: {
    breadcrumb: '素材库 / 人物素材',
    icon: '🧑',
    defaultGroup: '虚拟人像项目',
    pageTitle: '人物素材',
    pageDescription: '管理可用于视频出镜的人物素材；成品会同步到私域人物素材资产库。',
    steps: ['上传训练照片', '生成三视图成品', '同步私域入库'],
    addTitle: '新增虚拟人像',
    addHint: '创建虚拟人像档案并上传照片',
    nameLabel: '名称',
    namePlaceholder: '例如：品牌代言人、导购形象、知识博主',
    uploadTitle: '上传本人照片',
    uploadHint: '建议上传正脸、半身、不同角度的清晰照片；成品入库成功后可用于视频出镜',
    createOkText: '创建虚拟人像项目',
    emptyGroups: '暂无虚拟人像项目，可创建素材档案后上传照片。',
    emptyAssets: '该虚拟人像暂无照片或三视图素材，可以上传本人照片后继续生成。',
    detailUploadText: '上传照片',
    detailAddText: '添加照片',
    assetUnit: '张照片',
    accept: 'image/*',
  },
  voice: {
    breadcrumb: '素材库 / 人声素材',
    icon: '🎙️',
    defaultGroup: '克隆音库',
    pageTitle: '人声素材',
    pageDescription: '上传一段干净的人声音频，生成可复用的克隆音库；音库后续用于视频口播、试听和批量合成。',
    steps: ['上传人声音频', '生成克隆音色', '用于口播合成'],
    addTitle: '新增音库',
    addHint: '创建音库并上传样本',
    nameLabel: '音库名称',
    namePlaceholder: '例如：老板本人音色、温柔女声、专业讲解音',
    uploadTitle: '上传音频样本',
    uploadHint: '建议上传 30 秒以上、环境安静、单人说话的音频；支持继续补充样本提升稳定性',
    createOkText: '创建克隆音库',
    emptyGroups: '暂无克隆音库，可创建音库后上传声音样本。',
    emptyAssets: '该音库暂无音频样本，可以上传干净人声后继续克隆。',
    detailUploadText: '上传样本',
    detailAddText: '添加样本',
    assetUnit: '段音频',
    accept: 'audio/*',
  },
  scene: {
    breadcrumb: '素材库 / 场景素材',
    icon: '🎬',
    defaultGroup: '场景分组',
    pageTitle: '场景素材',
    pageDescription: '管理可用于视频背景、产品展示和氛围切换的图片素材；按场景分组，方便在视频生成流程中快速选择。',
    steps: ['创建场景分组', '上传图片素材', '视频中选择使用'],
    addTitle: '新增场景分组',
    addHint: '创建分组并上传图片',
    nameLabel: '场景分组名称',
    namePlaceholder: '例如：直播间背景、门店环境、产品展示台',
    uploadTitle: '上传场景图片',
    uploadHint: '建议上传横图或竖图场景图片，可按空间、渠道、活动主题建立分组',
    createOkText: '创建场景分组',
    emptyGroups: '暂无场景分组，可创建分组后管理图片素材。',
    emptyAssets: '该分组暂无场景图片，可以点击“上传图片”添加。',
    detailUploadText: '上传图片',
    detailAddText: '添加图片',
    assetUnit: '张图片',
    accept: 'image/*',
  },
  product: {
    breadcrumb: '素材库 / 产品素材',
    icon: '📦',
    defaultGroup: '产品素材',
    pageTitle: '产品素材',
    pageDescription: '管理产品图片、卖点图和展示素材，供视频制作引用。',
    steps: ['创建产品分组', '上传产品素材', '视频中引用'],
    addTitle: '新增分组',
    addHint: '创建分组并上传素材',
    nameLabel: '分组名称',
    namePlaceholder: '例如：产品套装、主推 SKU、活动素材',
    uploadTitle: '选择素材文件',
    uploadHint: '可先创建空分组，也可同时上传素材',
    createOkText: '创建并上传',
    emptyGroups: '暂无素材分组，可创建分组后上传素材。',
    emptyAssets: '该分组暂无素材，可上传素材后继续完善。',
    detailUploadText: '上传素材',
    detailAddText: '添加素材',
    assetUnit: '个素材',
    accept: 'image/*',
  },
  finished_video: {
    breadcrumb: '作品',
    icon: '📁',
    defaultGroup: '作品',
    pageTitle: '作品',
    pageDescription: '查看和管理已生成成功的图片和视频。',
    steps: ['生成作品', '预览作品', '复用或删除'],
    addTitle: '新增作品',
    addHint: '作品由图片创作和视频生成自动产生',
    nameLabel: '作品名称',
    namePlaceholder: '作品名称',
    uploadTitle: '作品',
    uploadHint: '作品由图片创作和视频生成自动产生',
    createOkText: '确认',
    emptyGroups: '暂无生成成功的作品。',
    emptyAssets: '暂无生成成功的作品。',
    detailUploadText: '上传素材',
    detailAddText: '添加素材',
    assetUnit: '个作品',
    accept: 'video/*',
  },
  other: {
    breadcrumb: '素材库 / 其他素材',
    icon: '📁',
    defaultGroup: '其他素材',
    pageTitle: '其他素材',
    pageDescription: '管理其他可复用内容素材。',
    steps: ['创建分组', '上传素材', '内容中引用'],
    addTitle: '新增分组',
    addHint: '创建分组并上传素材',
    nameLabel: '分组名称',
    namePlaceholder: '例如：活动素材、辅助图片、通用文件',
    uploadTitle: '选择素材文件',
    uploadHint: '可先创建空分组，也可同时上传素材',
    createOkText: '创建并上传',
    emptyGroups: '暂无素材分组，可创建分组后上传素材。',
    emptyAssets: '该分组暂无素材，可上传素材后继续完善。',
    detailUploadText: '上传素材',
    detailAddText: '添加素材',
    assetUnit: '个素材',
    accept: '',
  },
};
