export type LlmModelPricingSeed = {
  id: string;
  provider: string;
  providerName: string;
  model: string;
  displayName: string;
  defaultBaseUrl: string;
  currency: 'USD' | 'CNY';
  inputPricePer1M: number;
  outputPricePer1M: number;
  cachedInputPricePer1M: number;
  priceSource: string;
  priceUpdatedAt: string;
  createdAt: string;
  updatedAt: string;
};

const seedDate = '2026-06-15';
const seedTimestamp = `${seedDate}T00:00:00.000Z`;

export const llmModelPricingSeeds: LlmModelPricingSeed[] = [
  {
    id: 'openai:gpt-4.1-mini',
    provider: 'openai',
    providerName: 'OpenAI',
    model: 'gpt-4.1-mini',
    displayName: 'GPT-4.1 Mini',
    defaultBaseUrl: 'https://api.openai.com/v1',
    currency: 'USD',
    inputPricePer1M: 0.4,
    outputPricePer1M: 1.6,
    cachedInputPricePer1M: 0.1,
    priceSource: 'openai-official',
    priceUpdatedAt: seedDate,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: 'openai-compatible:gpt-4.1-mini',
    provider: 'OpenAI Compatible',
    providerName: 'OpenAI Compatible',
    model: 'gpt-4.1-mini',
    displayName: 'GPT-4.1 Mini',
    defaultBaseUrl: 'https://api.openai.com/v1',
    currency: 'USD',
    inputPricePer1M: 0.4,
    outputPricePer1M: 1.6,
    cachedInputPricePer1M: 0.1,
    priceSource: 'openai-official',
    priceUpdatedAt: seedDate,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: 'openai:gpt-4.1',
    provider: 'openai',
    providerName: 'OpenAI',
    model: 'gpt-4.1',
    displayName: 'GPT-4.1',
    defaultBaseUrl: 'https://api.openai.com/v1',
    currency: 'USD',
    inputPricePer1M: 2,
    outputPricePer1M: 8,
    cachedInputPricePer1M: 0.5,
    priceSource: 'openai-official',
    priceUpdatedAt: seedDate,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: 'openai:gpt-4o',
    provider: 'openai',
    providerName: 'OpenAI',
    model: 'gpt-4o',
    displayName: 'GPT-4o',
    defaultBaseUrl: 'https://api.openai.com/v1',
    currency: 'USD',
    inputPricePer1M: 2.5,
    outputPricePer1M: 10,
    cachedInputPricePer1M: 1.25,
    priceSource: 'openai-official',
    priceUpdatedAt: seedDate,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: 'deepseek:deepseek-chat',
    provider: 'deepseek',
    providerName: 'DeepSeek',
    model: 'deepseek-chat',
    displayName: 'DeepSeek Chat',
    defaultBaseUrl: 'https://api.deepseek.com',
    currency: 'CNY',
    inputPricePer1M: 2,
    outputPricePer1M: 8,
    cachedInputPricePer1M: 0.5,
    priceSource: 'deepseek-official',
    priceUpdatedAt: seedDate,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: 'deepseek:deepseek-reasoner',
    provider: 'deepseek',
    providerName: 'DeepSeek',
    model: 'deepseek-reasoner',
    displayName: 'DeepSeek Reasoner',
    defaultBaseUrl: 'https://api.deepseek.com',
    currency: 'CNY',
    inputPricePer1M: 4,
    outputPricePer1M: 16,
    cachedInputPricePer1M: 1,
    priceSource: 'deepseek-official',
    priceUpdatedAt: seedDate,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: 'deepseek:deepseek-v4-pro',
    provider: 'deepseek',
    providerName: 'DeepSeek',
    model: 'deepseek-v4-pro',
    displayName: 'DeepSeek V4 Pro',
    defaultBaseUrl: 'https://api.deepseek.com',
    currency: 'CNY',
    inputPricePer1M: 3,
    outputPricePer1M: 6,
    cachedInputPricePer1M: 0.025,
    priceSource: 'deepseek-official',
    priceUpdatedAt: seedDate,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: 'volcengine:doubao-seed-1-6',
    provider: 'volcengine',
    providerName: '火山方舟',
    model: 'doubao-seed-1-6',
    displayName: '豆包 Seed 1.6',
    defaultBaseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    currency: 'CNY',
    inputPricePer1M: 1.5,
    outputPricePer1M: 9,
    cachedInputPricePer1M: 0.15,
    priceSource: 'volcengine-official',
    priceUpdatedAt: seedDate,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
  {
    id: 'volcengine-cn:doubao-seed-2-0-pro-260215',
    provider: '火山引擎',
    providerName: '火山方舟',
    model: 'doubao-seed-2-0-pro-260215',
    displayName: '豆包 Seed 2.0 Pro',
    defaultBaseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    currency: 'CNY',
    inputPricePer1M: 3.2,
    outputPricePer1M: 16,
    cachedInputPricePer1M: 0.64,
    priceSource: 'volcengine-official',
    priceUpdatedAt: seedDate,
    createdAt: seedTimestamp,
    updatedAt: seedTimestamp,
  },
];
