export const routePaths = {
  login: '/login',
  appRoot: '/app',
  defaultLanding: '/app/content/video_remake',
  defaultModule: '/app/image',
  module: (moduleId = ':moduleId') => `/app/modules/${moduleId}`,
  contentRoot: '/app/content',
  contentDefault: '/app/content/create_video',
  contentModule: (moduleCode = ':moduleCode') => `/app/content/${moduleCode}`,
  xingtuCreators: '/app/creator-ops/xingtu',
  buyinCreators: '/app/creator-ops/buyin',
  douyinCreators: '/app/creator-ops/douyin',
  creatorFavorites: '/app/creator-ops/favorites',
  wechatOps: '/app/creator-ops/wechat',
  account: '/app/account',
  systemSettings: '/app/system-settings',
  noPermission: '/app/no-permission',
};
